### ISSUE TITLE
MacOS build problems hopefully fixed, binary wheel support

### ISSUE THREAD

**Issue by mreineck** [conda-forge/ducc0-feedstock#22]
This is just a heads-up that I recently managed to fix a compilation issue on MacOS, which apparently caused failures in this repo. Starting from version 0.19 this will hopefully be gone.

Also, there is now a workflow in the upstream package which can produce binary wheels. I'm not sure whether this affects the packaging process for conda in any way, but I thought I'd mention it nevertheless.

**Comment by ickc** [comment]
Thanks! Resolved in #23.
